#!/usr/bin/env bash

source ./bin/utils.sh

shopt -s globstar

requires bc aplay soxi cut || die "Required applications are not installed"

percentComplete()
{
    local start=${1}
    local duration=${2}

    echo "scale = 2; (${SECONDS} - ${start}) / ${duration}" | bc 
}

playSong()
{
    local song="${@}"
    aplay "${song}"
}

while [[ -n "${@}" ]]; do
    album="${1}"
    shift

    if [[ -d "${album}" ]]; then
        for song in "${album}"/**/*.wav; do
            songDuration=$(soxi -D "${song}" | cut -d. -f1)
            progress "playSong ${song}" "percentComplete ${SECONDS} ${songDuration}" "Now playing: ${song}"
        done
    elif [[ -f "${album}" ]]; then
        songDuration=$(soxi -D "${album}" | cut -d. -f1)
        progress "playSong ${album}" "percentComplete ${SECONDS} ${songDuration}" "Now playing: ${album}"
    fi
done
